spring.application.name=product-service-projekt2
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt-public-key=${JWT_PUBLIC_URL}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.forward-headers-strategy=framework